- src/ApiApprover/ApiApprover.csproj
- src/ApiApprover/packages.config
- src/ApiApproverTests/ApiApproverTests.csproj
- src/ApiApproverTests/packages.config
- src/PublicApiGenerator/ApiGenerator.cs
- src/PublicApiGenerator/PublicApiGenerator.csproj
- src/PublicApiGenerator/PublicApiGenerator.nuspec
- src/PublicApiGenerator/packages.config
can we get a beta release with this change?
> Mono.Cecil.0.10.0-beta5

- src/ApiApproverTests/ApiGeneratorTestsBase.cs
- src/ApiApproverTests/Namespaces_whitelisting.cs
- src/PublicApiGenerator/ApiGenerator.cs
Fixes #32 by introducing an option to pass white-listed namespace prefixes.
@danielmarbach please review
> Enable namespace whitelisting

- GitVersion.yml
- src/PublicApiGenerator/ApiGenerator.cs
- src/PublicApiGeneratorTests/ApiGeneratorTestsBase.cs
- src/PublicApiGeneratorTests/Class_attributes.cs
- src/PublicApiGeneratorTests/Class_event_attributes.cs
- src/PublicApiGeneratorTests/Delegate_attributes.cs
- src/PublicApiGeneratorTests/Field_attributes.cs
- src/PublicApiGeneratorTests/Interface_attributes.cs
- src/PublicApiGeneratorTests/Interface_event_attributes.cs
- src/PublicApiGeneratorTests/Interface_method_attributes.cs
- src/PublicApiGeneratorTests/Interface_method_return_value_attributes.cs
- src/PublicApiGeneratorTests/Method_attributes.cs
- src/PublicApiGeneratorTests/Method_parameter_attributes.cs
- src/PublicApiGeneratorTests/Method_return_value_attributes.cs
- src/PublicApiGeneratorTests/Property_attributes.cs
- src/PublicApiGeneratorTests/Struct_attributes.cs
> Attributes exclusion

- GitVersion.yml
- src/PublicApiGenerator/ApiGenerator.cs
> Remove whitespace

- README.md
Referenced example was removed in cb98d14ad8aabc4e482bea1c25a95608dbc251db
> Remove obsolete example

- README.md
- src/ApiApprover.sln
- src/ApiApprover/PublicApiApprover.cs
- src/PublicApiGenerator.Tool/Program.cs
- src/PublicApiGenerator/ApiGenerator.cs
- src/PublicApiGeneratorTests/Field_modifiers.cs
Hey. I saw this project in tests for Castle.Core and got interested. Looking through the code I noticed several typos.
> Code cleanup

- src/PublicApiGenerator/ApiGenerator.cs
- src/PublicApiGeneratorTests/Method_extensions.cs
- src/PublicApiGeneratorTests/Method_generics.cs
Closes, #67
Replaces https://github.com/JakeGinnivan/ApiApprover/pull/68
> Add Generic constraints

- src/PublicApiGenerator/ApiGenerator.cs
- src/PublicApiGeneratorTests/Method_extensions.cs
fixes #67
@JakeGinnivan, @danielmarbach  I am not sure about the correctness of the fix. Previously, I did not work with Mono.Cecil and not aware of its object model. Edits were done experimentally.
> Add generic constraint

- src/PublicApiGenerator/ApiGenerator.cs
- src/PublicApiGeneratorTests/Method_parameters.cs
> Fix closed generic out parameters

- .github/workflows/ci.yml
- build.cmd
> Make windows CI fail when tests fail

- src/PublicApiGenerator/ApiGenerator.cs
- src/PublicApiGenerator/AttributeFilter.RequiredAttributeNames.cs
- src/PublicApiGenerator/AttributeFilter.SkippedAttributeNames.cs
- src/PublicApiGenerator/AttributeFilter.cs
- src/PublicApiGeneratorTests/Well_known_attributes.cs
Replaces https://github.com/ApiApprover/ApiApprover/pull/119
Fixes #117
> Compiler attributes

- src/PublicApiGenerator/CodeNormalizer.cs
- src/PublicApiGeneratorTests/Class_constructors.cs
- src/PublicApiGeneratorTests/Struct_readonly.cs
@danielmarbach We need beta-4 :)
> fix readonly struct ctor

- src/Directory.Build.props
- src/PublicApiGenerator.Tool/Program.cs
- src/PublicApiGenerator/ApiGenerator.cs
- src/PublicApiGenerator/AttributeFilter.cs
- src/PublicApiGenerator/CodeTypeReferenceBuilder.cs
- src/PublicApiGenerator/NullableContext.cs
- src/PublicApiGeneratorTests/ApiGeneratorTestsBase.cs
- src/PublicApiGeneratorTests/Class_constructors.cs
- src/PublicApiGeneratorTests/Class_nested.cs
- src/PublicApiGeneratorTests/Dynamics.cs
- src/PublicApiGeneratorTests/Interface_methods.cs
- src/PublicApiGeneratorTests/Method_parameters.cs
- src/PublicApiGeneratorTests/NullableTests.cs
I think this is the entirety of the public API:
```cs
namespace PublicApiGenerator
{
public static class ApiGenerator
{
public static string GeneratePublicApi(
Assembly assembly,
Type[]? includeTypes = null,
bool shouldIncludeAssemblyAttributes = true,
string[]? whitelistedNamespacePrefixes = null,
string[]? excludeAttributes = null);
}
}
```
> Add nullability annotations

- src/PublicApiGenerator/ApiGenerator.cs
- src/PublicApiGeneratorTests/Interface_methods.cs
I am surprised that we have not noticed this before.
> Use true/false insted of True/False

- src/PublicApiGenerator/CodeNormalizer.cs
- src/PublicApiGeneratorTests/Event_modifiers.cs
> Event protected

- src/PublicApiGenerator/EventNameBuilder.cs
- src/PublicApiGenerator/MethodNameBuilder.cs
- src/PublicApiGeneratorTests/Event_modifiers.cs
- src/PublicApiGeneratorTests/Method_modifiers.cs
Outcome of https://twitter.com/danielmarbach/status/1197062217730056192
> Align modifier order

- src/PublicApiGenerator/ApiGenerator.cs
- src/PublicApiGenerator/CecilEx.cs
- src/PublicApiGenerator/CodeNormalizer.cs
- src/PublicApiGenerator/EventNameBuilder.cs
- src/PublicApiGenerator/MethodNameBuilder.cs
- src/PublicApiGenerator/ModifierMarkerNameBuilder.cs
- src/PublicApiGenerator/PropertyNameBuilder.cs
- src/PublicApiGeneratorTests/Property_modifiers.cs
> Support for property modifiers

- src/PublicApiGenerator.Tool/Program.cs
With this PR (borrowed from #177), I'd like to propose changing the project XML string replacements (that's hard to read and maintain) with strong-typed XML tree building. It also has the benefit of replacing 3 intertwined string fields (`ProjectTemplate`, `PackageReferenceTemplate` and `ProjectReferenceTemplate`) with a single and self-contained function that is now `SaveProject`.
I have also renamed `CreateProjectTemplate` and `SaveProjectTemplate` to `CreateProject` and `SaveProject` since they deal with the _actual_ project rather than a project's template.
> Refactor project creation using strong XML model

- README.md
- src/PublicApiGenerator.Tool/Program.cs
Fixes https://github.com/PublicApiGenerator/PublicApiGenerator/issues/176
> Support for package-source

- src/PublicApiGenerator/ApiGenerator.cs
- src/PublicApiGeneratorTests/Class_attributes.cs
- src/PublicApiGeneratorTests/HelperTypes.cs
> Fix special case for Flags attribute

- .github/labeler.yml
- .github/workflows/cd-preview.yml
- .github/workflows/cd-release.yml
- .github/workflows/ci.yml
- .github/workflows/label.yml
- src/PublicApiGenerator.sln
> Add labeler workflow

- .github/workflows/codeql-analysis.yml
- .github/workflows/dependency-review.yml
- src/PublicApiGenerator.sln
> Add CodeQL and Dependency Review workflows

- src/Directory.Build.props
- src/PublicApiGenerator/AttributeNameBuilder.cs
- src/PublicApiGenerator/EventNameBuilder.cs
- src/PublicApiGenerator/MethodNameBuilder.cs
- src/PublicApiGenerator/PropertyNameBuilder.cs
- src/PublicApiGeneratorTests/Method_parameters.cs
- src/PublicApiGeneratorTests/PublicApiGenerator.approved.txt
I'm sure all these classes were public occasionally. I don’t think it is worth increasing the major version of the package because of this .
> Fix visibility for internal classes

- src/PublicApiGenerator/PublicApiGenerator.csproj
- src/PublicApiGenerator/System.CodeDom/CSharpCodeGenerator.cs
- src/PublicApiGenerator/System.CodeDom/CSharpCodeProvider.cs
- src/PublicApiGenerator/System.CodeDom/CSharpHelpers.cs
- src/PublicApiGenerator/System.CodeDom/ExposedTabStringIndentedTextWriter.cs
- src/PublicApiGenerator/System.CodeDom/StringExtensions.cs
https://github.com/PublicApiGenerator/PublicApiGenerator/issues/153#issuecomment-2571659121
> Initial commit of System.CodeDom files

- src/PublicApiGenerator/PublicApiGenerator.csproj
- src/PublicApiGeneratorTests/Method_order.cs
> Bump System.CodeDom to 9.0.0

- src/PublicApiGenerator/CodeNormalizer.cs
bug-fix for https://github.com/PublicApiGenerator/PublicApiGenerator/issues/301 is not needed anymore
> Handle even more new lines gracefully

- src/PublicApiGenerator/DynamicContext.cs
- src/PublicApiGenerator/System.CodeDom/CSharpCodeGenerator.cs
- src/PublicApiGeneratorTests/Delegate_types.cs
- src/PublicApiGeneratorTests/Dynamics.cs
> Add support for dynamic keyword

- src/PublicApiGenerator/ApiGenerator.cs
- src/PublicApiGenerator/System.CodeDom/CSharpCodeGenerator.cs
- src/PublicApiGeneratorTests/Constants.cs
> Handle more special characters

- src/PublicApiGenerator/CecilEx.CopyPasted.cs
> Fix StackOverflowException

- src/PublicApiGenerator/ApiGenerator.cs
- src/PublicApiGenerator/CecilEx.cs
- src/PublicApiGenerator/CodeTypeReferenceBuilder.cs
- src/PublicApiGenerator/Declarations/CodeMemberFieldEx.cs
- src/PublicApiGenerator/Declarations/CodeParameterDeclarationExpressionEx.cs
- src/PublicApiGenerator/NullableMode.cs
- src/PublicApiGenerator/System.CodeDom/CSharpCodeGenerator.cs
- src/PublicApiGeneratorTests/Issue459.cs
> Handle Nullable<T> gracefully
