PublicApiGenerator/PublicApiGenerator

src/ApiApprover/PublicApiGenerator.cs
src/ApiApproverTests/Class_attributes.cs
src/ApiApproverTests/HelperTypes.cs

Case:
[MyAttribute(X)]
[MyAttribute(Y)]
[MyAttribute(Z)]
class MyClass {
...
}
Problem: order of attributes was not deterministic - test that passed on local PC was failing on build machine because of changed order. 
Solution: I haven't looked for the root cause - decided to just add secondary explicit sorting.

Fix - now multiple declaration of the same attribute will be always in the same order

---

src/ApiApprover/ApiApprover.csproj
src/ApiApprover/ExampleApiApprovalTest.cs
src/ApiApprover/PublicApiApprover.cs
src/ApiApprover/PublicApiGenerator.cs
src/ApiApprover/packages.config
src/ApiApproverTests/Properties/AssemblyInfo.cs

Namer fix: Instead of duplicating the logic in ApprovalTests for determining the path, I just had the custom namer inherit from the default one.
Also, added `AssemblyInformationalVersionAttribute` to the list of ignored attributes.

Namer fix + ignoring infoversion attribute

---

build.proj
src/ApiApprover/ApiApprover.nuspec

fixes #10
i also removed ExampleApiApprovalTest from the package. i think doco is a better place for that and it will break for anyone not using xunit

use App_Packages convention

---

src/ApiApproverTests/Class_hierarchy.cs
src/PublicApiGenerator/PublicApiGenerator.cs

See
https://twitter.com/terrajobst/status/773905057909645315
Internal interfaces declared on a class are not part of the public API.

Internal interfaces on class are not part of public API

---

src/ApiApprover/PublicApiGenerator.cs

Rendering constants with CultureInfo.InvariantCulture to avoid trouble with non en-\* systems. This issue came up while working with the [Humanizer project](https://github.com/Humanizr/Humanizer/pull/475).

Rendering constants with CultureInfo.InvariantCulture

---

src/PublicApiGenerator/PublicApiGenerator.cs

GetMethod was passed to PopulateCustomAttributes instead of SetMethod

Correction of a copy-paste error when processing Properties

---

build.proj
src/ApiApproverTests/Method_async.cs
src/PublicApiGenerator/ApiGenerator.cs
src/PublicApiGenerator/PublicApiGenerator.nuspec

Closes #19 
The async keyword should not be part of the public API at all.
The async keyword is an implementation detail since it is just syntactic sugar. From an API perspective the following APIs are equivalent:
- `async void` vs. `void`
- `async Task` vs `Task`
- `async Task<T>` vs `Task<T>`
From a behavior perspective you could argue that the runtime behavior from `void` to `async void` can change and therefore it could be a breaking change but from an API perspective both APIs are binary compatible. Since API approver's concern is only the public API the `async` keyword should be omitted.

Async keyword is not part of the public API

---

src/ApiApprover/ApiApprover.nuspec
src/PublicApiGenerator/PublicApiGenerator.nuspec

@danielmarbach This updates the nuspec files to include the source files in the `contentFiles` folder as well as `content`. This let the packages work when installed in a project that uses NuGet's transitive restore mechanism, for example via PackageReference in the new SDK-style csproj format.
I've intentionally removed the version number from the `contentFiles` path because these will be refereenced from the NuGet package cache folder, which already includes the version number.

Add support for contentFiles

---

src/PublicApiGenerator/ApiGenerator.cs

Supersedes #35 
NUnit creates a lot of directories for the assemblies, meaning it's hard for the ApiGenerator to find dependencies. By adding *AppDomain.CurrentDomain.BaseDirectory* as search directory, it will have the *actual output directory* of the test project as search directory making sure that dependencies can be found when running using NUnit.

Add AppDomain.CurrentDomain.BaseDirectory to assembly search path

---

src/PublicApiGenerator/ApiGenerator.cs
src/PublicApiGeneratorTests/Namespaces_whitelisting.cs

I noticed that while whitelisting works for "Microsoft" prefixes it wasn't allowing whitelisting to override the filtering of "System" prefixes.

Fix whitelisting System namespaces

---

src/PublicApiGenerator/ApiGenerator.cs
src/PublicApiGeneratorTests/Operator_order.cs
src/PublicApiGeneratorTests/Operator_visibility.cs

I noticed that operators are not currently included in the generated public api surface whereas I would expect operators to be included. This was the result of `IsSpecialName` returning `true` for operators.
Unfortunately there doesn't appear to be a good way to tell whether this is a "special name" that should be included or not (such as the case for operators). I confess I'm not sure what all falls under the "special name" category. The best differentiator I could find [was sources claiming that all operator names are formatted as "op_*"](https://stackoverflow.com/a/3016653/558700) so I leveraged that for determining if a given method is an operator. I'm very open to alternatives that can be more precise without needing to rely on string comparisons.
I'm willing to write more tests but …

Include operators in api generation

---

src/PublicApiGenerator/PublicApiGenerator.csproj

At the moment 0.10 of Cecil only supports portable PDB and full PDBs
They added support for the embedded files in v0.10.1 version of Mono.Cecil
Updating the reference to allow for this.
The current workaround is easy in terms of I can just update my project but thought others might benefit from this.
Thanks :)

Update Mono.Cecil to 0.10.1 to allow Embedded debug type

---

src/PublicApiGenerator/ApiGenerator.cs
src/PublicApiGeneratorTests/Assembly_member_ordering.cs
src/PublicApiGeneratorTests/Class_member_order.cs
src/PublicApiGeneratorTests/Class_order.cs
src/PublicApiGeneratorTests/Field_order.cs
src/PublicApiGeneratorTests/Interface_member_order.cs
src/PublicApiGeneratorTests/Interface_order.cs
src/PublicApiGeneratorTests/Method_order.cs
src/PublicApiGeneratorTests/Struct_member_order.cs
src/PublicApiGeneratorTests/Struct_order.cs

 Use StringComparer.Ordinal instead of linguistic culture aware ordering which can lead to different results depending on the environment

---

src/PublicApiGenerator/ApiGenerator.cs
src/PublicApiGeneratorTests/Class_generics.cs

Fix type attribute handling

---

src/PublicApiGenerator/ApiGenerator.cs
src/PublicApiGeneratorTests/Field_visibility.cs
src/PublicApiGeneratorTests/Method_visibility.cs
src/PublicApiGeneratorTests/Property_visibility.cs

At the moment members marked with the `protected internal` access modifier are output inconsistently:
- Fields get no modifier
- Methods and properties get `protected internal`
Since the `internal` part of `protected internal` doesn't apply to the public API, I think all `protected internal` members should be output like they are just marked `protected`.
I've provided a fix and added/updated unit tests. Let me know if there is anything else you'd like me to do.

Output protected internal access modifier as protected

---

src/PublicApiGenerator/ApiGenerator.cs
src/PublicApiGeneratorTests/PublicApiGeneratorTests.csproj
src/PublicApiGeneratorTests/Struct_readonly.cs

Rudimentary readonly struct support

---

src/PublicApiGenerator/ApiGenerator.cs
src/PublicApiGeneratorTests/Class_constructors.cs
src/PublicApiGeneratorTests/Interface_method_parameters.cs
src/PublicApiGeneratorTests/Method_parameters.cs
src/PublicApiGeneratorTests/PublicApiGeneratorTests.csproj

Rudimentary in modifier support

---

src/PublicApiGenerator/ApiGenerator.cs
src/PublicApiGeneratorTests/Method_parameters.cs

I noticed that ApiApprover generates `CancellationToken token = null` for such common API like `public static Task DoSomething(CancellationToken token = default)`. It's obvious that `null` is invalid default value for struct.

Add support for default keyword for non primitive structs

---

src/PublicApiGenerator/PublicApiGenerator.csproj
src/PublicApiGeneratorTests/Assembly_attributes.cs
src/PublicApiGeneratorTests/PublicApiGeneratorTests.csproj

Removes support for NET4.0 and switches to .NET Standard only

Remove net40

---

src/PublicApiGenerator/ApiGenerator.cs
src/PublicApiGeneratorTests/Field_types.cs

Fixes issue when 
`public readonly System.Func<a,b,c,d> Some;`
become
`public readonly System.Func<a Some;`
@danielmarbach I stumbled upon this by accident. I localized the problem - it happens if the control falls into the `ModifyCodeTypeReference` method. If `typeReference` has any `TypeArguments` then after call to `new CodeTypeReference(modifier + " " + provider.GetTypeOutput(typeReference))` there are 0 `TypeArguments` in newly created `CodeTypeReference`. Well, then comes complete nonsense.
If you call a constructor that accepts second argument - `params CodeTypeReference[] typeArguments`, then the output changes (`int` -> `System.Int32`, `string` -> `System.String` and so on) and some tests fail.
I used a simple if condition and made all the tests work. But I **do not like it**. …

Weird readonly Func

---

.editorconfig
README.md
src/ApiApprover.sln
src/Directory.Build.props
src/PublicApiGenerator.Tool/Program.cs
src/PublicApiGenerator/ApiGenerator.cs
src/PublicApiGenerator/CSharpAlias.cs
src/PublicApiGenerator/CodeTypeReferenceBuilder.cs
src/PublicApiGenerator/NullableContext.cs
src/PublicApiGenerator/NullableMode.cs
src/PublicApiGenerator/PublicApiGenerator.csproj
src/PublicApiGeneratorTests/ApiGeneratorTestsBase.cs
src/PublicApiGeneratorTests/Class_nested.cs
src/PublicApiGeneratorTests/Dynamics.cs
src/PublicApiGeneratorTests/Field_modifiers.cs
src/PublicApiGeneratorTests/NullableTests.cs
src/PublicApiGeneratorTests/PublicApiGeneratorTests.csproj

C# 8 nullable reference type support
volatile without modreq
fixes #54 
fixes #108
fixes #107
readme note + .editorconfig
unmanaged and notnull constraints
This is final rebased and squashed version of #102

C# 8 nullable reference type support

---

src/PublicApiGenerator/ApiGenerator.cs
src/PublicApiGenerator/CSharpTypeKeyword.cs
src/PublicApiGenerator/CodeTypeReferenceBuilder.cs
src/PublicApiGeneratorTests/Field_modifiers.cs
src/PublicApiGeneratorTests/Method_modifiers.cs
src/PublicApiGeneratorTests/PublicApiGeneratorTests.csproj

Replaces https://github.com/ApiApprover/ApiApprover/pull/114

Add unsafe modifier when necessary

---

src/PublicApiGenerator/ApiGenerator.cs
src/PublicApiGenerator/CSharpOperatorKeyword.cs
src/PublicApiGenerator/CecilEx.cs
src/PublicApiGenerator/CodeNormalizer.cs
src/PublicApiGeneratorTests/Field_modifiers.cs

Move all "small"/"helper" methods from ApiGenerator to extensions to keep it clean
fixes #116

Add syntax for volatile fields

---

src/PublicApiGenerator/ApiGenerator.cs
src/PublicApiGenerator/CecilEx.cs
src/PublicApiGeneratorTests/Class_constructors.cs
src/PublicApiGeneratorTests/Class_nested.cs
src/PublicApiGeneratorTests/Event_visibility.cs
src/PublicApiGeneratorTests/Field_visibility.cs
src/PublicApiGeneratorTests/Keyword_order.cs
src/PublicApiGeneratorTests/Method_visibility.cs
src/PublicApiGeneratorTests/Property_visibility.cs

Fixes #109. 
I set out to fix `famandassem` members which should not be shown. They have been able to be created in .NET assemblies since the beginning.
While writing tests, I discovered that tests were missing for the visibility of events and nested `protected internal` types. I added them and they failed, so this PR fixes two additional issues:
- Events were being included and shown as `public` regardless of visibility, including private ones.
- Nested `protected internal` types were excluded even though they appear as `protected` types from outside the assembly.

Fix visibility issues with events, nested types, and 'private protected'

---

src/PublicApiGenerator/PublicApiGenerator.csproj

A .snupkg file will now appear in the build artifacts. When you do `nuget push Foo.nupkg`, it automatically pushes `Foo.snupkg` as long as it is still in the same folder. More details at https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg#publishing-a-symbol-package.
Make sure that when you push, the NuGet source URL that you're pushing to is a v3 URL (`https://api.nuget.org/v3/index.json`), not a v2 URL, or this will not happen.
To step into ApiApprover code from a consuming project like Shouldly, all that is required is to temporarily turn off [Debug > Options > Enable Just My Code](https://docs.microsoft.com/en-us/visualstudio/debugger/just-my-code) and make sure that the VS2019 default NuGet Symbol Server option is still enabled:

Enable debugger source-stepping

---

src/PublicApiGenerator/ApiGenerator.cs
src/PublicApiGenerator/CodeNormalizer.cs
src/PublicApiGenerator/EventNameBuilder.cs
src/PublicApiGeneratorTests/Event_modifiers.cs
src/PublicApiGeneratorTests/Interface_event_attributes.cs
src/PublicApiGeneratorTests/Interface_events.cs
src/PublicApiGeneratorTests/Interface_member_order.cs
src/PublicApiGeneratorTests/Method_modifiers.cs
src/PublicApiGeneratorTests/Property_modifiers.cs

Event modifier support

---

src/PublicApiGenerator/ApiGenerator.cs
src/PublicApiGenerator/AttributeNameBuilder.cs
src/PublicApiGeneratorTests/Indexer_properties.cs

Closes #106
I think soon I will need to cleanup the dependencies between the names and the code normalizer a bit but for now the name uses the markers defined on the normalizer

Propagate DefaultMemberAttribute to IndexerNameAttribute

---

src/PublicApiGenerator/CodeTypeDeclarationExtensions.cs
src/PublicApiGeneratorTests/Method_order.cs

This tweaks the output to slightly more closely match what Intellisense does: simpler members (with less params) first and more complex members (with more params) later.

sort members on parameter count

---

src/PublicApiGenerator/ApiGenerator.cs
src/PublicApiGenerator/CodeNormalizer.cs
src/PublicApiGenerator/CodeTypeDeclarationExtensions.cs
src/PublicApiGenerator/EventNameBuilder.cs
src/PublicApiGenerator/MethodNameBuilder.cs
src/PublicApiGeneratorTests/Method_modifiers.cs

Support for more method scenarios for #112

Support for more method modifiers

---

src/PublicApiGenerator/MethodNameBuilder.cs
src/PublicApiGeneratorTests/Method_modifiers.cs

An issue that I found comparing API Diff of Azure Service Bus SDK

Method param matching

---

src/PublicApiGenerator/ApiGenerator.cs
src/PublicApiGeneratorTests/Indexer_properties.cs

regression in #136 
I was very surprised when I saw this :)
```c# public interface IMessageProperties
{
[System.Runtime.CompilerServices.IndexerName("Item")]
string Item { get; }
[System.Runtime.CompilerServices.IndexerName("Item")]
string Item { get; }
[System.Runtime.CompilerServices.IndexerName("Item")]
string Item { get; }
[System.Runtime.CompilerServices.IndexerName("Item")]
string Item { get; }
[System.Runtime.CompilerServices.IndexerName("Item")]
System.DateTime? Item { get; }
[System.Runtime.CompilerServices.IndexerName("Item")]
System.DateTime? Item { get; }
object this[string key] { get; }
[System.Runtime.CompilerServices.IndexerName("Item")]
string Item { get; }
[System.Runtime.CompilerServices.IndexerName("Item")]
string Item { get; } …
```

Output property eventhough indexer exists

---

src/PublicApiGenerator/ApiGenerator.cs
src/PublicApiGeneratorTests/Method_parameters.cs

Such a method
```c#
public TType Method<TType>(string name, TType defaultValue = default)
```
before this change was written as
```c#
public TType Method<TType>(string name, TType defaultValue = null)
```

Change default value from 'null' to 'default' for generic parameter

---

build.cmd

This PR fixes issue #164 by changing the current working directory to that of the project at the start. The `setlocal` will ensure that the current working directory is restored when the batch terminates (successfully or unsuccessfully).

Fix Windows build script to CD to project directory

---

src/PublicApiGenerator.Tool/Program.cs

Running the tool with `--help` before this PR:
```
Usage:
PublicApiGenerator.Tool [options]
Options:
--target-frameworks <TARGET-FRAMEWORKS>    targetFrameworks
--assembly <ASSEMBLY>                      assembly
--project-path <PROJECT-PATH>              projectPath
--package <PACKAGE>                        package
--package-version <PACKAGE-VERSION>        packageVersion
--generator-version <GENERATOR-VERSION>    generatorVersion
--working-directory <WORKING-DIRECTORY>    workingDirectory
--output-directory <OUTPUT-DIRECTORY>      outputDirectory
--verbose <VERBOSE>                        verbose
--leave-artifacts <LEAVE-ARTIFACTS>        leaveArtifacts
--version                                  Display version information
```
Note that descriptions of arguments is not being picked up …

Fix tool help to show descriptions of arguments

---

src/PublicApiGenerator.Tool/Program.cs

_Some_ errors would be sent to `STDOUT` as well as _all_ logging.
This PR consistently sends logging and errors to `STDERR` as opposed to having a mixed case of the two.

Consistently write errors & log to standard error

---

src/PublicApiGenerator.Tool/Program.cs
src/PublicApiGenerator.Tool/PublicApiGenerator.Tool.csproj
src/PublicApiGenerator.Tool/SubProgram.cs

Borrowing from #177, I'd like to propose moving the generator sub-program source code into a separate file that's embedded as a resource as opposed to a string literal to help with maintenance, validation and easier reading (syntax highlighting).
Also note that I removed the unnecessary `public` modifiers from the sub-program's `Program` and `Main` (thus defaulting to `internal`). If you prefer to record that as a separate edit/commit then I can split it from this PR.

Embed sub-program source as a resource

---

README.md
src/PublicApiGenerator.Tool/Program.cs
src/PublicApiGenerator.Tool/SubProgram.cs

This PR addresses #173.
Replaces #180 
The _worker_ project's `Program.Main` takes two parameters only: the source assembly path and the output API file path. If the latter is `-` then the API is generated to standard output. It also logs unhandled exceptions to standard error and sets an exit code on success or failure. It is no longer the responsibility of the worker project to do any file operations like deleting and moving. This is done by PublicApiGenerator.
If `dotnet run` times out (after 10 seconds, which seems short to be honest) then an exception is thrown. Previously, PublicApiGenerator continue silently.

Generate API on STDOUT when single target framework given

---

src/PublicApiGenerator/PropertyNameBuilder.cs
src/PublicApiGeneratorTests/Indexer_properties.cs

Tests for, and fixes, #188... but I don't know what collateral damage this may produce, as my understanding of `PropertyNameBuilder.AugmentPropertyNameWithPropertyModifierMarkerTemplate` is rather incomplete. While all existing tests still pass, I could easily be breaking some yet untested use cases.

Fix output for abstract get-set indexers

---

src/PublicApiGenerator/ApiGenerator.cs
src/PublicApiGeneratorTests/Class_attributes.cs

Repro unit test and fix for #190.
~~Marking this as a draft, as I might add more commits later and convert this into a bugfix PR.~~
Fixes #190.

Ensure that `SerializableAttribute` gets reproduced in output

---

src/PublicApiGenerator/CSharpOperatorKeyword.cs
src/PublicApiGeneratorTests/Operator_order.cs
src/PublicApiGeneratorTests/Operator_visibility.cs

Fix syntax for overloaded operator methods

---

src/PublicApiGenerator/ApiGenerator.cs
src/PublicApiGeneratorTests/Class_attributes.cs

Resolves #214.
There's one tricky bit that doesn't get resolved here. Say we have these definitions:
```csharp
[Flags]
public enum Letters
{
A = 1,
B = 2,
C = 4,
AB = A | B,
All = A | B | C,
}
public class LettersAttribute : Attribute
{
public LettersAttribute(Letters letters) { }
}
[Letters(Letters.All)]
public class Test { }
```
Should the emitted API for `Test` mention only `[Letters(Letters.All)]`, or `[Letters(Letters.A | Letters.B | Letters.AB | Letters.All)]`? Perhaps the latter, as `All` encompasses all other flags and results in terser output. Finding the minimal set of flags might be quite tricky (or at least computationally more expensive), so I'm leaving that to a future PR for now.

When determining flag combination, match only flags having all of their bits set

---

src/PublicApiGenerator/ApiGenerator.cs

This change help me to workaround for #213 (using reflection, using my custom filtration, on my own risk, but I can be able to do it).
Also it doesn't expose ability to generate api text for internal member.
Also this change will get code bit more cleaner (single place for filter types) (I hope).
This change join two predicates which are used to determine which types will be included in result into single one.
Originally part of the predicate was in `GeneratePublicApi` method, another part - in `CreatePublicApiForAssembly` (internal method). 
Now method `CreatePublicApiForAssembly` will receive full predicate from method `GeneratePublicApi`.

Pull up type condition (which type will be included in result)

---

src/PublicApiGenerator/CodeTypeReferenceBuilder.cs
src/PublicApiGeneratorTests/Expressions.cs

Before this fix such ctor
`public ClassWithExpressions(params Expression<Func<int, object>>[] expr1) { }`
yields
` public ClassWithExpressions(params System.Linq.Expressions.Expression<>[]? expr1) { }`
After fix generator yields
`public ClassWithExpressions(params System.Linq.Expressions.Expression<System.Func<int, object>>[] expr1)`

Fix generic arguments for array types

---

.github/workflows/ci.yml
src/PublicApiGenerator/ApiGenerator.cs
src/PublicApiGeneratorTests/ApiGeneratorTestsBase.cs
src/PublicApiGeneratorTests/Assembly_attributes.cs
src/PublicApiGeneratorTests/IsExternalInit.cs
src/PublicApiGeneratorTests/PublicApiGeneratorTests.csproj
src/PublicApiGeneratorTests/Record.cs

Fix inconsistencies for record types across NET 6.x.x SDK

---

src/PublicApiGenerator/ApiGenerator.cs
src/PublicApiGenerator/CodeNormalizer.cs
src/PublicApiGeneratorTests/Property_methods.cs
src/PublicApiGeneratorTests/Record.cs

Closes #250.
Not sure if this is the best way to get this done (probably not!), but for now it appears to work.

Add support for C# 9 init-only setters

---

.github/workflows/cd-preview.yml
.github/workflows/cd-release.yml
.github/workflows/ci.yml
README.md
src/Directory.Build.props
src/PublicApiGenerator.sln
src/PublicApiGeneratorTests/PublicApiGeneratorTests.csproj

Fixes #258 
This PR adds 3 workflows:
- `ci` to run tests for pull requests without publish any artifacts
- `cd-preview` to pack/publish nuget packages to GitHub registry on each push into `master`
- `cd-release` to pack/publish nuget packages to nuget.org when publishing release from GitHub

Add CI/CD workflows

---

src/Directory.Build.props
src/PublicApiGenerator.Tool/PublicApiGenerator.Tool.csproj
src/PublicApiGenerator/ApiGenerator.cs
src/PublicApiGenerator/PublicApiGenerator.csproj

fixes #277 
It was due to how/when MSBuild resolves `IsPackable` value.

Fix readme in nupkg

---

src/PublicApiGenerator/CodeNormalizer.cs
src/PublicApiGeneratorTests/Assembly_attributes.cs
src/PublicApiGeneratorTests/Issue301.cs
src/PublicApiGeneratorTests/PublicApiGeneratorTests.csproj

Fix issue with dropped semicolon on NET472

---

README.md

The `UsesVerify` attribute is [no longer required](https://github.com/VerifyTests/Verify/pull/1131) and it can be removed.

Update the Verify.Xunit example

---

src/PublicApiGenerator/ApiGeneratorOptions.cs

Ignore XamlGeneratedNamespace by default

---

src/PublicApiGenerator/ApiGenerator.cs
src/PublicApiGenerator/AttributeFilter.RequiredAttributeNames.cs
src/PublicApiGenerator/CecilEx.cs
src/PublicApiGenerator/System.CodeDom/CSharpCodeGenerator.cs
src/PublicApiGeneratorTests/Delegate_types.cs
src/PublicApiGeneratorTests/NativeIntegers.cs

@stakx mentioned `nint` and `nuint` in #207
Note that since .NET7 `nint` is a true alias for `System.IntPtr` and `nuint` is a true alias for `System.UIntPtr`.

Support native sized integers
